name: 'Publish Docker Image'
description: 'Publish Docker Image'

runs:
  using: "composite"
  steps:

  - name: Log in to registry with Docker
    shell: bash
    run: |
      echo "${{ github.token }}" | docker login ghcr.io/${{ github.repository }} -u ${{ github.actor }} --password-stdin

  - name: Push image
    shell: bash
    run: |
      export IMG=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
      export REPOSITORY=ghcr.io
      make docker-buildx
